// <auto-generated />
namespace CodeFirstExistingDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191133001_deletedproperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
